### ISSUE TITLE
`metatensor.torch.Labels` cannot be pickled

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#452] opened 2024-01-20 23:04 UTC
When I try to export a model in `metatensor.models`, I get

```
RuntimeError: Cannot serialize custom bound C++ class __torch__.torch.classes.metatensor.Labels. Please define serialization methods via def_pickle() for this class.
```

**Comment by Luthaf** [comment] 2024-01-22 09:31
Duplicate of https://github.com/lab-cosmo/metatensor/issues/321

**Closed by Luthaf** 2024-01-22 09:31 UTC
