### ISSUE TITLE
ASE calculator reuse

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#468] opened 2024-02-01 04:14 UTC
It might be a good idea to return the same values for the energy/forces if the configuration hasn't changed since the last calculation of the ASE calculator. According to ChatGPT, many ASE calculators do this

**Comment by sirmarcel** [comment] 2024-02-01 07:58
Yes, as far as I know this is expected behaviour. ASE supplies some functionality for this in https://gitlab.com/ase/ase/-/blob/master/ase/calculators/calculator.py?ref_type=heads#L84. Here's what I did for GLP: https://github.com/sirmarcel/glp/blob/f9406c75d577d1702d2d98cf1b07f5317776fd43/glp/ase/calculator.py#L160

**Comment by Luthaf** [comment] 2024-02-01 10:53
I though this was handled by ˋCaluculator.calculateˋ automatically, in particular through the ˋsystem_changes` parameter. You are saying we should handle this manually?

**Comment by sirmarcel** [comment] 2024-02-01 11:07
Okay, I've taken a look at the `ase` code -- as far as I can tell, the `get_property` method defined in the class that `MetatensorCalculator` inherits from (`ase.calculators.calculator.Calculator`) does this check, but the `calculate` method doesn't check it. So you need to decide if this is something you want do handle in `calculate` yourself or rely on `ase` to do it automatically. In what situation is this a problem?

**Comment by sirmarcel** [comment] 2024-02-01 11:49
Sorry, I'm not sure I was clear enough: I believe that currently, calling `atoms.get_forces()` or similar with the `MetatensorCalculator` attached will *not* trigger a recomputation because `get_property` already checks for changes and only triggers `calculate` if no change has occurred. So, two questions:

1) Did you notice that this it not the case and do you want to flag this as a problem with this issue?
2) Is this not the behaviour that you want? Should `calculate` separately check for changes?

If neither apply, I'd close this issue.

**Comment by Luthaf** [comment] 2024-02-01 15:20
The caching seems to be working fine at ASE level, so there might be something else going on here

```py
class CallsCounter(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.call_count = 0

    def forward(
        self,
        systems: List[System],
        outputs: Dict[str, ModelOutput],
        selected_atoms: Optional[Labels],
    ) -> Dict[str, TensorMap]:
        self.call_count += 1

        if "energy" not in outputs:
            return {}

        samples = Labels(
            ["structure"],
            torch.tensor([[s] for s in range(len(systems))], dtype=torch.int32),
        )
        block = TensorBlock(
            values=torch.zeros(len(systems), 1),
            samples=samples,
            components=[],
            properties=Labels(["energy"], torch.IntTensor([[0]])),
        )
        return {
            "energy": TensorMap(Labels(["_"], torch.IntTensor([[0]])), [block]),
        }


def test_caching(atoms):
    counter = CallsCounter()
    counter.train(False)

    capabilities = ModelCapabilities(
        length_unit="Angstrom",
        species=[28],
        outputs={
            "energy": ModelOutput(
                quantity="energy",
                unit="eV",
                per_atom=False,
                explicit_gradients=[],
            ),
        },
    )

    model = MetatensorAtomisticModel(counter, capabilities)

    atoms.calc = MetatensorCalculator(model)

    assert counter.call_count == 0
    atoms.get_potential_energy()
    assert counter.call_count == 1

    # Getting the energy again should not call the model again
    atoms.get_potential_energy()
    assert counter.call_count == 1

    atoms.get_kinetic_energy()
    assert counter.call_count == 1

    atoms.get_total_energy()
    assert counter.call_count == 1
```

**Comment by sirmarcel** [comment] 2024-02-01 19:39
So, this test passes? In that case, I'm not sure what the problem is...?

**Comment by frostedoyster** [comment] 2024-02-02 13:51
I would make a release following this wave of bug fixes, try to re-run an MD exercise, and see what happens

**Comment by Luthaf** [comment] 2024-02-21 18:54
closing for now, we can re-open if there is still a bug

**Closed by Luthaf** 2024-02-21 18:54 UTC
Labels: Atomistic-Models
