### ISSUE TITLE
Model fails when used with different atomic types

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#713] opened 2024-08-09 17:17 UTC
This leads to models breaking as they can't find the definitions of `Labels`, etc. I wonder if there is a way to load the library automatically when using the module where `load_atomistic_model` is defined

**Comment by Luthaf** [comment] 2024-08-09 17:48
That's very weird. The function is defined in the same Python module that should load the extension. Could you share some reproducing code?

**Comment by frostedoyster** [comment] 2024-08-11 13:33
I also found it weird, but it was found by @sofiia-chorna and it was fixed by importing `metatensor.torch` at the top of the file

**Comment by sofiia-chorna** [comment] 2024-08-12 08:07
Hello! I attached the jupyter notebook with the reproduction of the bug.
[bug_reproduction.zip](https://github.com/user-attachments/files/16578776/bug_reproduction.zip)

The error occurs when the dataset includes atomic numbers that the model has not encountered during training. If we filter out frames with these "unknown" atomic numbers, the error disappears. So I suppose that the issue is likely not related to the `metatensor.torch` import but rather to the presence of unseen atomic numbers in the data


```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[5], [line 18](vscode-notebook-cell:?execution_count=5&line=18)
      [6](vscode-notebook-cell:?execution_count=5&line=6)     systems_with_neighbors.append(get_system_with_neighbor_lists(
      [7](vscode-notebook-cell:?execution_count=5&line=7)         system, requested_neighbor_lists
      [8](vscode-notebook-cell:?execution_count=5&line=8)     ))
     [10](vscode-notebook-cell:?execution_count=5&line=10) evaluation_options = ModelEvaluationOptions(
     [11](vscode-notebook-cell:?execution_count=5&line=11)     length_unit="angstrom",
     [12](vscode-notebook-cell:?execution_count=5&line=12)         outputs={
   (...)
     [15](vscode-notebook-cell:?execution_count=5&line=15)         selected_atoms=None,
     [16](vscode-notebook-cell:?execution_count=5&line=16)     )
---> [18](vscode-notebook-cell:?execution_count=5&line=18) outputs = model(systems_with_neighbors, evaluation_options, check_consistency=False)
     [20](vscode-notebook-cell:?execution_count=5&line=20) llf = outputs["mtt::aux::last_layer_features"]
     [21](vscode-notebook-cell:?execution_count=5&line=21) llf = llf.block().values.detach().cpu().numpy()

File ~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1532, in Module._wrapped_call_impl(self, *args, **kwargs)
   [1530](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1530)     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   [1531](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1531) else:
-> [1532](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1532)     return self._call_impl(*args, **kwargs)

File ~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1541, in Module._call_impl(self, *args, **kwargs)
   [1536](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1536) # If we don't have any hooks, we want to skip the rest of the logic in
   [1537](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1537) # this function, and just call forward.
   [1538](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1538) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
...
            ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        module_idx: int = position
        module: ModuleMapInterface = self[module_idx]
builtins.KeyError: key <__torch__.torch.classes.metatensor.LabelsEntry object at 0x560411092f10> not found in modules.
```

**Comment by sofiia-chorna** [comment] 2024-08-12 08:17
However, there was another error, but I'm not sure if it is an expected issue!

For example, the extensions directory has incorrect path, like:
```
from metatensor.torch.atomistic import load_atomistic_model

model = load_atomistic_model("model.pt", extensions_directory="extensions-not-found/")
```

It raises exception:
```
[W model.cpp:795] Warning: failed to load extension dependency rascaline. We tried the following:
 - extensions-not-found//rascaline/lib/librascaline.so
 - loading rascaline directly by name
You can set `METATENSOR_DEBUG_EXTENSIONS_LOADING=1` in your environemnt for more information
 (function load_library)
[W model.cpp:795] Warning: failed to load TorchScript extension rascaline_torch. We tried the following:
 - extensions-not-found//rascaline/torch/lib/librascaline_torch.so
 - loading rascaline_torch directly by name
You can set `METATENSOR_DEBUG_EXTENSIONS_LOADING=1` in your environemnt for more information
 (function load_library)
[W model.cpp:887] Warning: The model at 'model.pt' was exported with extension 'rascaline_torch' loaded (from 'rascaline/torch/lib/librascaline_torch.so'), but it does not seem to be currently loaded; proceed at your own risk. (function check_atomistic_model)
```

This can be fixed by importing `import rascaline.torch` at the top, indeed.

**Comment by Luthaf** [comment] 2024-08-12 13:49
Ok, this is indeed unrelated to `metatensor.torch`not being loaded. The second error is expected, we need to load the rascaline_torch extension since the model is using it, and in Python this can be done with either `extensions_directory` or `import rascaline.torch`, although I would favor `extensions_directory` since it works everywhere.

The first error seems to be related to missing keys in your model, and if your model is based on rascaline's SOAP Power spectrum without additional transformation it will indeed fail.

It should however fail earlier than this. How are you calling the model? If you are calling it manually, you should check [`ModelCapabilities.atomic_types`](https://docs.metatensor.org/latest/atomistic/reference/models/metadata.html#metatensor.torch.atomistic.ModelCapabilities.atomic_types) for the set of atomic types the model can use.

If you are using [`ase_calculator.MetatensorCalculator`](https://docs.metatensor.org/latest/atomistic/reference/ase.html), then this check will be done for you. For the chemiscope application, I would recommend using [`run_model`](https://docs.metatensor.org/latest/atomistic/reference/ase.html#metatensor.torch.atomistic.ase_calculator.MetatensorCalculator.run_model), which will handle everything for you.

**Comment by sofiia-chorna** [comment] 2024-08-12 14:43
Thanks a lot for your answer!

Before indeed I was calling the model manually.

By the way, I tried to provide the atoms with some unseen atomic types to the `run_model`, it seems to not catch it as well:

```
from metatensor.torch.atomistic.ase_calculator import MetatensorCalculator
from metatensor.torch.atomistic import ModelOutput


mtt_model = MetatensorCalculator("model.pt")
outputs = {"mtt::aux::last_layer_features": ModelOutput(per_atom=True)}
mtt_model.run_model(atoms, outputs)
```

Error logs:
```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[51], [line 5](vscode-notebook-cell:?execution_count=51&line=5)
      [1](vscode-notebook-cell:?execution_count=51&line=1) from metatensor.torch.atomistic import ModelEvaluationOptions, ModelOutput  # noqa: E[4](vscode-notebook-cell:?execution_count=51&line=4)02
      4 requested = {"mtt::aux::last_layer_features": ModelOutput(per_atom=True)}
----> [5](vscode-notebook-cell:?execution_count=51&line=5) mtt_model.run_model(frames[0], requested)

File ~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:230, in MetatensorCalculator.run_model(self, atoms, outputs, selected_atoms)
    [223](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:223)     system.add_neighbor_list(options, neighbors)
    [225](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:225) options = ModelEvaluationOptions(
    [226](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:226)     length_unit="angstrom",
    [227](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:227)     outputs=outputs,
    [228](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:228)     selected_atoms=selected_atoms,
    [229](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:229) )
--> [230](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:230) return self._model(
    [231](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:231)     systems=[system],
    [232](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:232)     options=options,
    [233](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:233)     check_consistency=self.parameters["check_consistency"],
    [234](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/metatensor/torch/atomistic/ase_calculator.py:234) )

File ~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1532, in Module._wrapped_call_impl(self, *args, **kwargs)
   [1530](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1530)     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   [1531](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1531) else:
-> [1532](https://file+.vscode-resource.vscode-cdn.net/home/chorna/research/run-soap-bpnn/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1532)     return self._call_impl(*args, **kwargs)
...
            ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        module_idx: int = position
        module: ModuleMapInterface = self[module_idx]
builtins.KeyError: key <__torch__.torch.classes.metatensor.LabelsEntry object at 0x55e8546db080> not found in modules.
```

**Comment by Luthaf** [comment] 2024-08-12 15:51
Hmm. That's a soap-bpnn, right? @frostedoyster does metatrain set the right capabilities?

**Comment by frostedoyster** [comment] 2024-08-16 02:49
This has always worked for me, but we can check

**Comment by frostedoyster** [comment] 2024-08-16 07:22
Also, I think the error goes away (is replaced by a proper error) with `check_consistency=True` last time I checked with @sofiia-chorna, but with `check_consistency=False` that's what you get

**Comment by Luthaf** [comment] 2024-08-16 07:49
What's the error you get with `check_consistency=True`?

**Comment by sofiia-chorna** [comment] 2024-08-16 15:17
Here is the error with `check_consistency=True`:

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[4], [line 31](vscode-notebook-cell:?execution_count=4&line=31)
     [19](vscode-notebook-cell:?execution_count=4&line=19)     systems_with_neighbors.append(get_system_with_neighbor_lists(
     [20](vscode-notebook-cell:?execution_count=4&line=20)         system, requested_neighbor_lists
     [21](vscode-notebook-cell:?execution_count=4&line=21)     ))
     [23](vscode-notebook-cell:?execution_count=4&line=23) evaluation_options = ModelEvaluationOptions(
     [24](vscode-notebook-cell:?execution_count=4&line=24)     length_unit="angstrom",
     [25](vscode-notebook-cell:?execution_count=4&line=25)         outputs={
   (...)
     [28](vscode-notebook-cell:?execution_count=4&line=28)         selected_atoms=None,
     [29](vscode-notebook-cell:?execution_count=4&line=29)     )
---> [31](vscode-notebook-cell:?execution_count=4&line=31) outputs = model(systems_with_neighbors, evaluation_options, check_consistency=True)
     [33](vscode-notebook-cell:?execution_count=4&line=33) llf = outputs["mtt::aux::last_layer_features"]
     [34](vscode-notebook-cell:?execution_count=4&line=34) llf = llf.block().values.detach().cpu().numpy()

File ~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1532, in Module._wrapped_call_impl(self, *args, **kwargs)
   [1530](https://file+.vscode-resource.vscode-cdn.net/home/chorna/Downloads/bug_reproduction/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1530)     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   [1531](https://file+.vscode-resource.vscode-cdn.net/home/chorna/Downloads/bug_reproduction/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1531) else:
-> [1532](https://file+.vscode-resource.vscode-cdn.net/home/chorna/Downloads/bug_reproduction/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1532)     return self._call_impl(*args, **kwargs)

File ~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1541, in Module._call_impl(self, *args, **kwargs)
   [1536](https://file+.vscode-resource.vscode-cdn.net/home/chorna/Downloads/bug_reproduction/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1536) # If we don't have any hooks, we want to skip the rest of the logic in
   [1537](https://file+.vscode-resource.vscode-cdn.net/home/chorna/Downloads/bug_reproduction/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1537) # this function, and just call forward.
   [1538](https://file+.vscode-resource.vscode-cdn.net/home/chorna/Downloads/bug_reproduction/~/miniconda3/envs/research/lib/python3.12/site-packages/torch/nn/modules/module.py:1538) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
...
                    f"this model can not run for the atomic type '{atom_type.item()}'"
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                )
builtins.ValueError: this model can not run for the atomic type '16'
```

**Closed** 2024-08-26 07:52 UTC
Labels: Atomistic-Models
