### ISSUE TITLE
Device mismatch after calling `TensorMap.keys_to_samples()`

### ISSUE THREAD

**Issue by abmazitov** [lab-cosmo/metatensor#413] opened 2023-11-01 18:00 UTC
I guess that after the recent fix, calling `tensormap.keys_to_samples()` leads to change in internal values device, because the original device information is either lost or not used during the new tensormap initialization 

--- 

**Example**

```
print("tmap block values device: ", tensormap.block(0).values.device)
tensormap = tensormap.keys_to_samples("keys")
print("tmap block values device after k2s: ", tensormap.block(0).values.device)
```

will lead to the following output

```
tmap block values device:  cuda:0
tmap block values device after k2s:  cpu
```

**Comment by frostedoyster** [comment] 2023-11-01 19:11
I tried, but I get
```
tmap block values device:  cuda:0
tmap block values device after k2s:  cuda:0
```
Here is my script:
```
from metatensor.torch import Labels, TensorBlock, TensorMap
import torch


device = "cuda"
tensormap = TensorMap(
        keys=Labels.range("keys", 2).to(device),
        blocks=[
            TensorBlock(
                values=torch.tensor([[[1.0, 2.0]]], device=device),
                samples=Labels.range("samples", 1).to(device),
                components=[Labels.range("component", 1).to(device)],
                properties=Labels.range("properties", 2).to(device),
            ),
            TensorBlock(
                values=torch.tensor([[[3.0, 4.0]]], device=device),
                samples=Labels.range("samples", 1).to(device),
                components=[Labels.range("component", 1).to(device)],
                properties=Labels.range("properties", 2).to(device),
            ),
        ],
    )

print("tmap block values device: ", tensormap.block(0).values.device)
tensormap = tensormap.keys_to_samples("keys")
print("tmap block values device after k2s: ", tensormap.block(0).values.device)
```

Could you try the same and see what you get? You might be working with an older commit (in that case, that's a torch_spex bug)

**Comment by abmazitov** [comment] 2023-11-01 20:34
I tried to run this example, and everything works as you said. It turns out, that the problem is caused by keys stored on cpu and used as a provider for a device to the resulting tensor after keys_to_samples. 

I suppose that the issue may be caused by torch spex, which somehow creates the tensormap with keys on cpu

**Comment by abmazitov** [comment] 2023-11-01 21:09
Okay, there we go

One need to explicitly move the keys to `cuda` device, otherwise they will be stored on cpu, and everything will end up on cpu after `keys_to_samples`

---

**Example**

```
from metatensor.torch import Labels, TensorBlock, TensorMap
import torch


device = "cuda"
tensormap = TensorMap(
        keys=Labels.range("keys", 2).to(device),
        blocks=[
            TensorBlock(
                values=torch.tensor([[[1.0, 2.0]]], device=device),
                samples=Labels.range("samples", 1).to(device),
                components=[Labels.range("component", 1).to(device)],
                properties=Labels.range("properties", 2).to(device),
            ),
            TensorBlock(
                values=torch.tensor([[[3.0, 4.0]]], device=device),
                samples=Labels.range("samples", 1).to(device),
                components=[Labels.range("component", 1).to(device)],
                properties=Labels.range("properties", 2).to(device),
            ),
        ],
    )

test_tensormap = TensorMap(
    keys=Labels.range("keys", 2),
    blocks=[
        TensorBlock(
            values=torch.tensor([[[1.0, 2.0]]], device=device),
            samples=Labels.range("samples", 1).to(device),
            components=[Labels.range("component", 1).to(device)],
            properties=Labels.range("properties", 2).to(device),
        ),
        TensorBlock(
            values=torch.tensor([[[3.0, 4.0]]], device=device),
            samples=Labels.range("samples", 1).to(device),
            components=[Labels.range("component", 1).to(device)],
            properties=Labels.range("properties", 2).to(device),
        ),
    ],
)

print("tmap block values device: ", tensormap.block(0).values.device)
print("tmap keys device: ", tensormap.keys.values.device)
tensormap = tensormap.keys_to_samples("keys")
print("tmap block values device after k2s: ", tensormap.block(0).values.device)
print("tmap keys device after k2s: ", tensormap.keys.values.device)

print("test tmap block values device: ", test_tensormap.block(0).values.device)
print("test tmap keys device: ", test_tensormap.keys.values.device)
test_tensormap = test_tensormap.keys_to_samples("keys")
print("test tmap block values device after k2s: ", test_tensormap.block(0).values.device)
print("test tmap keys device after k2s: ", test_tensormap.keys.values.device)
```

results in the following output

```
tmap block values device:  cuda:0
tmap keys device:  cuda:0
tmap block values device after k2s:  cuda:0
tmap keys device after k2s:  cuda:0
test tmap block values device:  cuda:0
test tmap keys device:  cpu
test tmap block values device after k2s:  cpu
test tmap keys device after k2s:  cpu
```

**Comment by abmazitov** [comment] 2023-11-01 21:11
I guess this is exactly what's happening with me right now, because the `SphericalExpansion` calculator in the `torch_spex` doesn't move the keys to 'cuda' right now

```
spherical_expansion = TensorMap(
    keys = Labels(
        names = ["a_i", "lam", "sigma"],
        values = torch.tensor(labels, dtype=torch.int32)
    ),
    blocks = blocks
)

return spherical_expansion
```

**Comment by frostedoyster** [comment] 2023-11-01 21:57
Wow, two bugs in two different packages working together to ruin your day @abmazitov.
The torch_spex bug is clear, I'll fix it soon.
What do you think the behavior should be in this case @Luthaf?

**Comment by abmazitov** [comment] 2023-11-01 22:50
It ok, I fixed everything, and now it works ^^
IMO, we should raise an error while initializing the TensorMap if devices of keys, samples, properties, etc. are not consistent

**Comment by ceriottm** [comment] 2023-11-01 23:30
I agree, devices should be consistent at creation time. I can't see use cases to have different pieces on different devices.

**Comment by frostedoyster** [comment] 2023-11-02 06:18
Perhaps to distribute calculations. Some blocks could live in `cuda:0`, others in `cuda:1`, and so on

**Comment by Luthaf** [comment] 2023-11-02 11:31
This is then a duplicate of https://github.com/lab-cosmo/metatensor/issues/370, I'll close it as such.

**Closed by Luthaf** 2023-11-02 11:31 UTC
Labels: bug, Torch-API
